# EmbedShaderSource.cmake — run in `cmake -P` script mode by CompileShader.cmake's compile_shader()
# after glslangValidator has already produced ${IMF_SHADER_SPV}.
#
# Emits a generated header containing:
#   - the shader's raw GLSL source, as a C++ raw string literal (for GL3's own GLSL path and
#     for debugging what glslangValidator actually compiled)
#   - the compiled SPIR-V binary, as a constexpr byte array (for Vulkan/WebGPU/DX12/Metal
#     backends, once a later sub-phase feeds it to a real graphics API or to SPIRV-Cross)
#
# Expects: IMF_SHADER_SOURCE, IMF_SHADER_SPV, IMF_SHADER_SYMBOL, IMF_SHADER_HEADER.

if(NOT EXISTS "${IMF_SHADER_SPV}")
    message(FATAL_ERROR "EmbedShaderSource: expected glslangValidator to have produced ${IMF_SHADER_SPV}")
endif()

file(READ "${IMF_SHADER_SOURCE}" IMF_SOURCE_TEXT)
file(READ "${IMF_SHADER_SPV}" IMF_SPV_HEX HEX)

# One-shot global regex replace — far faster than a per-byte foreach(RANGE ...) loop in CMake
# script mode, and produces "0xNN, 0xNN, ..." directly from the hex-encoded byte stream.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " IMF_SPV_BYTES "${IMF_SPV_HEX}")
string(LENGTH "${IMF_SPV_HEX}" IMF_HEX_LEN)
math(EXPR IMF_SPV_BYTE_COUNT "${IMF_HEX_LEN} / 2")

file(WRITE "${IMF_SHADER_HEADER}" "\
#pragma once
// Auto-generated by cmake/EmbedShaderSource.cmake from ${IMF_SHADER_SOURCE} — do not edit by hand.

#include <cstddef>

namespace ImFrame::Internal::Shaders {

inline constexpr const char* k${IMF_SHADER_SYMBOL}Source = R\"IMF_GLSL(
${IMF_SOURCE_TEXT})IMF_GLSL\";

alignas(4) inline constexpr unsigned char k${IMF_SHADER_SYMBOL}Spirv[] = {
    ${IMF_SPV_BYTES}
};

inline constexpr std::size_t k${IMF_SHADER_SYMBOL}SpirvByteCount = ${IMF_SPV_BYTE_COUNT};

} // namespace ImFrame::Internal::Shaders
")
