# EmbedShaderDXIL.cmake — run in `cmake -P` script mode by CompileShaderDXC.cmake's
# compile_shader_hlsl() after dxc.exe has already produced ${IMF_SHADER_DXIL}.
#
# Emits a generated header containing:
#   - the shader's raw HLSL source, as a C++ raw string literal (for debugging what dxc.exe
#     actually compiled)
#   - the compiled DXIL binary, as a constexpr byte array (for NativeRendererDX12)
#
# Mirrors cmake/EmbedShaderSource.cmake's own SPIR-V embed exactly, just named "Dxil" (not
# "Spirv") throughout so the two compiled-bytecode kinds are never confused by symbol name alone.
#
# Expects: IMF_SHADER_SOURCE, IMF_SHADER_DXIL, IMF_SHADER_SYMBOL, IMF_SHADER_HEADER.

if(NOT EXISTS "${IMF_SHADER_DXIL}")
    message(FATAL_ERROR "EmbedShaderDXIL: expected dxc.exe to have produced ${IMF_SHADER_DXIL}")
endif()

file(READ "${IMF_SHADER_SOURCE}" IMF_SOURCE_TEXT)
file(READ "${IMF_SHADER_DXIL}" IMF_DXIL_HEX HEX)

string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " IMF_DXIL_BYTES "${IMF_DXIL_HEX}")
string(LENGTH "${IMF_DXIL_HEX}" IMF_HEX_LEN)
math(EXPR IMF_DXIL_BYTE_COUNT "${IMF_HEX_LEN} / 2")

file(WRITE "${IMF_SHADER_HEADER}" "\
#pragma once
// Auto-generated by cmake/EmbedShaderDXIL.cmake from ${IMF_SHADER_SOURCE} — do not edit by hand.

#include <cstddef>

namespace ImFrame::Internal::Shaders {

inline constexpr const char* k${IMF_SHADER_SYMBOL}Source = R\"IMF_HLSL(
${IMF_SOURCE_TEXT})IMF_HLSL\";

alignas(4) inline constexpr unsigned char k${IMF_SHADER_SYMBOL}Dxil[] = {
    ${IMF_DXIL_BYTES}
};

inline constexpr std::size_t k${IMF_SHADER_SYMBOL}DxilByteCount = ${IMF_DXIL_BYTE_COUNT};

} // namespace ImFrame::Internal::Shaders
")
