name: Sanitizers

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  asan:
    name: AddressSanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "c0948694cceff995e5cf90b751e0c5a95d613458"
      - name: Configure
        env:
          CC: clang-17
          CXX: clang++-17
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" \
            -DIMF_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        env:
          ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
        run: ctest --test-dir build --output-on-failure

  tsan:
    name: ThreadSanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "c0948694cceff995e5cf90b751e0c5a95d613458"
      - name: Configure
        env:
          CC: clang-17
          CXX: clang++-17
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_CXX_FLAGS="-fsanitize=thread" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=thread" \
            -DIMF_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        env:
          TSAN_OPTIONS: abort_on_error=1
        run: ctest --test-dir build --output-on-failure

  ubsan:
    name: UndefinedBehaviourSanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "c0948694cceff995e5cf90b751e0c5a95d613458"
      - name: Configure
        env:
          CC: clang-17
          CXX: clang++-17
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_CXX_FLAGS="-fsanitize=undefined -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined" \
            -DIMF_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        env:
          UBSAN_OPTIONS: print_stacktrace=1:abort_on_error=1
        run: ctest --test-dir build --output-on-failure
